# Generated by Django 4.1.4 on 2022-12-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploads',
        ),
    ]
